import type { ArabicLetter } from '@/lib/huruf/types';

export const ARABIC_LETTERS: ArabicLetter[] = [
  {
    id: 'alif',
    order: 1,
    isolated: 'ا',
    name: 'Alif',
    transliteration: 'ā / a',
    audioSlug: 'alif',
    makhraj: 'Open throat — the letter carries vowel sounds.',
    example: 'Allah (الله)',
  },
  {
    id: 'ba',
    order: 2,
    isolated: 'ب',
    name: 'Ba',
    transliteration: 'b',
    audioSlug: 'ba',
    makhraj: 'Both lips pressed together, then released.',
    example: 'Bismillah (بسم)',
  },
  {
    id: 'ta',
    order: 3,
    isolated: 'ت',
    name: 'Ta',
    transliteration: 't',
    audioSlug: 'taa',
    makhraj: 'Tip of the tongue touches the upper front teeth.',
    example: 'Tawbah (توبة)',
  },
  {
    id: 'tha',
    order: 4,
    isolated: 'ث',
    name: 'Tha',
    transliteration: 'th',
    audioSlug: 'tha',
    makhraj: 'Tongue between the teeth — like “think” in English.',
    example: 'Thalatha (ثلاثة)',
  },
  {
    id: 'jim',
    order: 5,
    isolated: 'ج',
    name: 'Jim',
    transliteration: 'j',
    audioSlug: 'jeem',
    makhraj: 'Middle of the tongue rises to the hard palate.',
    example: 'Jannah (جنة)',
  },
  {
    id: 'ha',
    order: 6,
    isolated: 'ح',
    name: 'Ha',
    transliteration: 'ḥ',
    audioSlug: 'ha',
    makhraj: 'A breathy h from the middle of the throat.',
    example: 'Hamdu (حمد)',
  },
  {
    id: 'kha',
    order: 7,
    isolated: 'خ',
    name: 'Kha',
    transliteration: 'kh',
    audioSlug: 'khaa',
    makhraj: 'Back of the tongue with the soft palate — like Scottish “loch”.',
    example: 'Khair (خير)',
  },
  {
    id: 'dal',
    order: 8,
    isolated: 'د',
    name: 'Dal',
    transliteration: 'd',
    audioSlug: 'dal',
    makhraj: 'Tip of the tongue behind the upper front teeth.',
    example: 'Deen (دين)',
  },
  {
    id: 'dhal',
    order: 9,
    isolated: 'ذ',
    name: 'Dhal',
    transliteration: 'dh',
    audioSlug: 'dhal',
    makhraj: 'Tongue between the teeth — like “that” in English.',
    example: 'Dhikr (ذكر)',
  },
  {
    id: 'ra',
    order: 10,
    isolated: 'ر',
    name: 'Ra',
    transliteration: 'r',
    audioSlug: 'raa',
    makhraj: 'Tip of the tongue taps the palate — a rolling r.',
    example: 'Rabb (رب)',
  },
  {
    id: 'zay',
    order: 11,
    isolated: 'ز',
    name: 'Zay',
    transliteration: 'z',
    audioSlug: 'jaa',
    makhraj: 'Tip of the tongue near the upper teeth — like English z.',
    example: 'Zakah (زكاة)',
  },
  {
    id: 'sin',
    order: 12,
    isolated: 'س',
    name: 'Sin',
    transliteration: 's',
    audioSlug: 'seen',
    makhraj: 'Tongue tip near the lower teeth — a clear s sound.',
    example: 'Salam (سلام)',
  },
  {
    id: 'shin',
    order: 13,
    isolated: 'ش',
    name: 'Shin',
    transliteration: 'sh',
    audioSlug: 'sheen',
    makhraj: 'Middle of the tongue rises — like “sh” in English.',
    example: 'Shukr (شكر)',
  },
  {
    id: 'sad',
    order: 14,
    isolated: 'ص',
    name: 'Sad',
    transliteration: 'ṣ',
    audioSlug: 'saad',
    makhraj: 'Emphatic s — tongue raised, deeper resonance.',
    example: 'Sabr (صبر)',
  },
  {
    id: 'dad',
    order: 15,
    isolated: 'ض',
    name: 'Dad',
    transliteration: 'ḍ',
    audioSlug: 'dhaad',
    makhraj: 'Emphatic d — side of the tongue on upper molars. Unique to Arabic.',
    example: 'Din (دين)',
  },
  {
    id: 'ta-emphatic',
    order: 16,
    isolated: 'ط',
    name: "Ta (emphatic)",
    transliteration: 'ṭ',
    audioSlug: 'toa',
    makhraj: 'Emphatic t — tongue pressed firmly against the palate.',
    example: 'Taharah (طهارة)',
  },
  {
    id: 'za-emphatic',
    order: 17,
    isolated: 'ظ',
    name: "Za (emphatic)",
    transliteration: 'ẓ',
    audioSlug: 'dhaa',
    makhraj: 'Emphatic th — tongue between teeth with back tongue raised.',
    example: 'Dhul (ذو)',
  },
  {
    id: 'ayn',
    order: 18,
    isolated: 'ع',
    name: 'Ayn',
    transliteration: '‘',
    audioSlug: 'ain',
    makhraj: 'Deep throat constriction — no English equivalent. Practice slowly.',
    example: 'Ilm (علم)',
  },
  {
    id: 'ghayn',
    order: 19,
    isolated: 'غ',
    name: 'Ghayn',
    transliteration: 'gh',
    audioSlug: 'ghain',
    makhraj: 'Back of the tongue with the uvula — like a gargle or French r.',
    example: 'Ghafoor (غفور)',
  },
  {
    id: 'fa',
    order: 20,
    isolated: 'ف',
    name: 'Fa',
    transliteration: 'f',
    audioSlug: 'faa',
    makhraj: 'Lower lip touches the upper front teeth.',
    example: 'Fajr (فجر)',
  },
  {
    id: 'qaf',
    order: 21,
    isolated: 'ق',
    name: 'Qaf',
    transliteration: 'q',
    audioSlug: 'qaaf',
    makhraj: 'Back of the tongue on the soft palate — deeper than kaf.',
    example: 'Quran (قرآن)',
  },
  {
    id: 'kaf',
    order: 22,
    isolated: 'ك',
    name: 'Kaf',
    transliteration: 'k',
    audioSlug: 'kaaf',
    makhraj: 'Back of the tongue near the soft palate.',
    example: 'Khair (خير)',
  },
  {
    id: 'lam',
    order: 23,
    isolated: 'ل',
    name: 'Lam',
    transliteration: 'l',
    audioSlug: 'laam',
    makhraj: 'Tip of the tongue on the hard palate.',
    example: 'La ilaha (لا)',
  },
  {
    id: 'mim',
    order: 24,
    isolated: 'م',
    name: 'Mim',
    transliteration: 'm',
    audioSlug: 'meem',
    makhraj: 'Both lips closed — nasal when followed by shaddah.',
    example: 'Muhammad (محمد)',
  },
  {
    id: 'nun',
    order: 25,
    isolated: 'ن',
    name: 'Nun',
    transliteration: 'n',
    audioSlug: 'noon',
    makhraj: 'Tip of the tongue on the palate — nasal sound.',
    example: 'Noor (نور)',
  },
  {
    id: 'ha-end',
    order: 26,
    isolated: 'ه',
    name: 'Ha (light)',
    transliteration: 'h',
    audioSlug: 'haa',
    makhraj: 'Gentle breath from the throat — lighter than ح.',
    example: 'Huda (هدى)',
  },
  {
    id: 'waw',
    order: 27,
    isolated: 'و',
    name: 'Waw',
    transliteration: 'w / u',
    audioSlug: 'waw',
    makhraj: 'Lips rounded — w sound or long u vowel.',
    example: 'Wudu (وضو)',
  },
  {
    id: 'ya',
    order: 28,
    isolated: 'ي',
    name: 'Ya',
    transliteration: 'y / i',
    audioSlug: 'yaa',
    makhraj: 'Middle of the tongue on the palate — y sound or long i vowel.',
    example: 'Yawm (يوم)',
  },
];

export function getLetterById(id: string): ArabicLetter | undefined {
  return ARABIC_LETTERS.find((letter) => letter.id === id);
}
