import type { ZikrCategory } from '@/lib/zikr/types';

export const ZIKR_CATEGORIES = [
  {
    id: 'morning',
    icon: 'sun-o',
    title: {
      en: 'Morning adhkar',
      bs: 'Jutarnji zikrovi',
      de: 'Morgendhikr',
      tr: 'Sabah zikirleri',
      fr: 'Adhkar du matin',
      ar: 'أذكار الصباح',
      id: 'Zikir pagi',
    },
    description: {
      en: 'After Fajr until sunrise — from Hisn al-Muslim',
      bs: 'Poslije sabaha do izlaska sunca — iz Hisn al-Muslim',
      de: 'Nach dem Fajr bis Sonnenaufgang — aus Hisn al-Muslim',
      tr: 'Sabah namazından güneş doğuncaya kadar — Hisn al-Muslim\'den',
      fr: 'Après le Fajr jusqu\'au lever du soleil — de Hisn al-Muslim',
      ar: 'بعد صلاة الفجر حتى طلوع الشمس — من حصن المسلم',
      id: 'Setelah Subuh hingga terbit matahari — dari Hisn al-Muslim',
    },
  },
  {
    id: 'evening',
    icon: 'moon-o',
    title: {
      en: 'Evening adhkar',
      bs: 'Večernji zikrovi',
      de: 'Abenddhikr',
      tr: 'Akşam zikirleri',
      fr: 'Adhkar du soir',
      ar: 'أذكار المساء',
      id: 'Zikir petang',
    },
    description: {
      en: 'After Asr until Maghrib — from Hisn al-Muslim',
      bs: 'Poslije ikindije do akšama — iz Hisn al-Muslim',
      de: 'Nach dem Asr bis zum Maghrib — aus Hisn al-Muslim',
      tr: 'İkindi namazından akşam namazına kadar — Hisn al-Muslim\'den',
      fr: 'Après l\'Asr jusqu\'au Maghrib — de Hisn al-Muslim',
      ar: 'بعد صلاة العصر حتى المغرب — من حصن المسلم',
      id: 'Setelah Ashar hingga Maghrib — dari Hisn al-Muslim',
    },
  },
  {
    id: 'sleep',
    icon: 'bed',
    title: {
      en: 'Before sleep',
      bs: 'Prije spavanja',
      de: 'Vor dem Schlaf',
      tr: 'Uykudan önce',
      fr: 'Avant le sommeil',
      ar: 'قبل النوم',
      id: 'Sebelum tidur',
    },
    description: {
      en: 'Adhkar when going to bed',
      bs: 'Zikrovi pri odlasku na spavanje',
      de: 'Adhkar beim Zubettgehen',
      tr: 'Yatarken okunacak zikirler',
      fr: 'Adhkar au coucher',
      ar: 'أذكار عند النوم',
      id: 'Zikir saat hendak tidur',
    },
  },
  {
    id: 'waking',
    icon: 'bell-o',
    title: {
      en: 'Upon waking',
      bs: 'Pri buđenju',
      de: 'Beim Erwachen',
      tr: 'Uyanınca',
      fr: 'Au réveil',
      ar: 'عند الاستيقاظ',
      id: 'Saat bangun',
    },
    description: {
      en: 'What to say when you wake up',
      bs: 'Šta reći kada se probudite',
      de: 'Was man beim Aufwachen sagt',
      tr: 'Uyanınca söylenecekler',
      fr: 'Ce qu\'il faut dire en se réveillant',
      ar: 'ما يُقال عند الاستيقاظ',
      id: 'Apa yang diucapkan saat bangun tidur',
    },
  },
  {
    id: 'protection',
    icon: 'shield',
    title: {
      en: 'Protection & ruqyah',
      bs: 'Zaštita i ruqja',
      de: 'Schutz & Ruqya',
      tr: 'Koruma ve rukye',
      fr: 'Protection & ruqya',
      ar: 'الحماية والرقية',
      id: 'Perlindungan & ruqyah',
    },
    description: {
      en: 'Seeking Allah\'s protection from harm',
      bs: 'Traženje Allaahove zaštite od zla',
      de: 'Allahs Schutz vor Schaden suchen',
      tr: 'Allah\'tan zarardan korunma talebi',
      fr: 'Demander la protection d\'Allah contre le mal',
      ar: 'طلب حماية الله من الأذى',
      id: 'Memohon perlindungan Allah dari bahaya',
    },
  },
  {
    id: 'after-prayer',
    icon: 'check-circle',
    title: {
      en: 'After prayer',
      bs: 'Poslije namaza',
      de: 'Nach dem Gebet',
      tr: 'Namaz sonrası',
      fr: 'Après la prière',
      ar: 'بعد الصلاة',
      id: 'Setelah shalat',
    },
    description: {
      en: 'Dhikr after every obligatory salah',
      bs: 'Zikr poslije svakog farz namaza',
      de: 'Dhikr nach jedem Pflichtgebet',
      tr: 'Her farz namazdan sonra zikir',
      fr: 'Dhikr après chaque prière obligatoire',
      ar: 'ذكر بعد كل صلاة فريضة',
      id: 'Zikir setelah setiap shalat fardhu',
    },
  },
  {
    id: 'general',
    icon: 'repeat',
    title: {
      en: 'Daily dhikr',
      bs: 'Svakodnevni zikr',
      de: 'Täglicher Dhikr',
      tr: 'Günlük zikir',
      fr: 'Dhikr quotidien',
      ar: 'الذكر اليومي',
      id: 'Zikir harian',
    },
    description: {
      en: 'Essential remembrance throughout the day',
      bs: 'Osnovni zikrovi tokom dana',
      de: 'Wesentliche Ermahnung den Tag über',
      tr: 'Gün boyunca temel zikirler',
      fr: 'Rappel essentiel tout au long de la journée',
      ar: 'أذكار أساسية طوال اليوم',
      id: 'Dzikir penting sepanjang hari',
    },
  },
  {
    id: 'distress',
    icon: 'heart',
    title: {
      en: 'Anxiety & distress',
      bs: 'Tjeskoba i nevolja',
      de: 'Angst & Not',
      tr: 'Kaygı ve sıkıntı',
      fr: 'Anxiété & détresse',
      ar: 'الهم والكرب',
      id: 'Kecemasan & kesusahan',
    },
    description: {
      en: 'When worried, sad, or in difficulty',
      bs: 'Kada ste zabrinuti, tužni ili u nevolji',
      de: 'Bei Sorge, Trauer oder Schwierigkeiten',
      tr: 'Endişeli, üzgün veya zor durumda iken',
      fr: 'Quand on est inquiet, triste ou en difficulté',
      ar: 'عند القلق أو الحزن أو الشدة',
      id: 'Saat cemas, sedih, atau kesulitan',
    },
  },
  {
    id: 'travel',
    icon: 'plane',
    title: {
      en: 'Travel',
      bs: 'Putovanje',
      de: 'Reise',
      tr: 'Seyahat',
      fr: 'Voyage',
      ar: 'السفر',
      id: 'Perjalanan',
    },
    description: {
      en: 'Supplications for a journey',
      bs: 'Dove pri putovanju',
      de: 'Bittgebete für eine Reise',
      tr: 'Yolculuk duaları',
      fr: 'Invocations pour un voyage',
      ar: 'أدعية السفر',
      id: 'Doa untuk perjalanan',
    },
  },
  {
    id: 'eating',
    icon: 'cutlery',
    title: {
      en: 'Eating & drinking',
      bs: 'Jelo i piće',
      de: 'Essen & Trinken',
      tr: 'Yeme ve içme',
      fr: 'Manger & boire',
      ar: 'الأكل والشرب',
      id: 'Makan & minum',
    },
    description: {
      en: 'Before and after meals',
      bs: 'Prije i poslije jela',
      de: 'Vor und nach den Mahlzeiten',
      tr: 'Yemekten önce ve sonra',
      fr: 'Avant et après les repas',
      ar: 'قبل الطعام وبعده',
      id: 'Sebelum dan sesudah makan',
    },
  },
  {
    id: 'mosque',
    icon: 'building',
    title: {
      en: 'Mosque',
      bs: 'Džamija',
      de: 'Moschee',
      tr: 'Cami',
      fr: 'Mosquée',
      ar: 'المسجد',
      id: 'Masjid',
    },
    description: {
      en: 'When entering and leaving the masjid',
      bs: 'Pri ulasku i izlasku iz džamije',
      de: 'Beim Betreten und Verlassen der Moschee',
      tr: 'Camiye girerken ve çıkarken',
      fr: 'En entrant et en sortant de la mosquée',
      ar: 'عند دخول المسجد وخروجه',
      id: 'Saat masuk dan keluar masjid',
    },
  },
  {
    id: 'wudu',
    icon: 'tint',
    title: {
      en: 'Wudu',
      bs: 'Abdest',
      de: 'Wudu',
      tr: 'Abdest',
      fr: 'Ablutions',
      ar: 'الوضوء',
      id: 'Wudu',
    },
    description: {
      en: 'Remembrance after ablution',
      bs: 'Zikrovi poslije abdesta',
      de: 'Ermahnung nach der Reinigung',
      tr: 'Abdestten sonra zikir',
      fr: 'Rappel après les ablutions',
      ar: 'أذكار بعد الوضوء',
      id: 'Zikir setelah berwudu',
    },
  },
] as ZikrCategory[];
