import { ZIKR_CATEGORIES } from '@/lib/zikr/categories';
import type { ZikrItem } from '@/lib/zikr/types';

export const ZIKR_ITEMS: ZikrItem[] = [
  // ─── Morning ───────────────────────────────────────────────
  {
    id: 'morning-1',
    categoryId: 'morning',
    arabic: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'Asbahna wa asbahal-mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa \'ala kulli shay\'in qadir.',
    translation: {
      en: 'We have reached the morning and at this very time all sovereignty belongs to Allah. All praise is for Allah. None has the right to be worshipped except Allah, alone, without partner. To Him belongs all sovereignty and praise and He is over all things omnipotent.',
      bs: 'Došli smo do jutra i u ovo vrijeme sva vlast pripada Allahu. Sva hvala pripada Allahu. Nema boga osim Allaha, Jednog, bez partnera. Njemu pripada vlast i hvala i On je nad svim stvarima Svemoćan.',
    },
    reference: 'Muslim 2723',
    repeat: 1,
  },
  {
    id: 'morning-2',
    categoryId: 'morning',
    arabic: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ',
    transliteration: 'Allahumma bika asbahna, wa bika amsayna, wa bika nahya, wa bika namutu, wa ilaykan-nushur.',
    translation: {
      en: 'O Allah, by You we enter the morning and by You we enter the evening, by You we live and by You we die, and to You is the resurrection.',
      bs: 'Allahu moj, Tebe se držimo ujutro i Tebe se držimo navečer, Tebom živimo i Tebom umiremo, i Tebi je povratak.',
    },
    reference: 'Tirmidhi 3391 · Sahih',
    repeat: 1,
  },
  {
    id: 'morning-3',
    categoryId: 'morning',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: 'Allahumma anta rabbi la ilaha illa ant, khalaqtani wa ana \'abduk, wa ana \'ala \'ahdika wa wa\'dika mastata\'t, a\'udhu bika min sharri ma sana\'t, abu\'u laka bi ni\'matika \'alayya, wa abu\'u bi dhanbi faghfir li fa innahu la yaghfirudh-dhunuba illa ant.',
    translation: {
      en: 'Sayyid al-Istighfar: O Allah, You are my Lord. None has the right to be worshipped except You. You created me and I am Your servant. I abide by Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favour upon me and I acknowledge my sin, so forgive me, for none forgives sins except You.',
      bs: 'Gospodarski istigfar: Allahu moj, Ti si moj Gospodar. Nema boga osim Tebe. Ti si me stvorio i ja sam Tvoj rob. Držim se Tvog saveza i obećanja koliko mogu. Tražim utočište u Tebi od zla onoga što sam učinio. Priznajem Tvoju blagodat prema meni i priznajem svoj grijeh, pa mi oprosti, jer niko ne oprašta grijehe osim Tebe.',
    },
    reference: 'Bukhari 6306',
    repeat: 1,
    virtue: {
      en: 'Whoever says it with certainty in the morning and dies that day enters Paradise.',
      bs: 'Ko to izgovori ujutro s uvjerenjem i umre tog dana — ući će u Džennet.',
    },
  },
  {
    id: 'morning-4',
    categoryId: 'morning',
    arabic: 'سُبْحَانَ اللَّهِ',
    transliteration: 'SubhanAllah',
    translation: {
      en: 'Glory be to Allah.',
      bs: 'Slava Allahu.',
    },
    reference: 'Muslim 597',
    repeat: 33,
  },
  {
    id: 'morning-5',
    categoryId: 'morning',
    arabic: 'الْحَمْدُ لِلَّهِ',
    transliteration: 'Alhamdulillah',
    translation: {
      en: 'All praise is for Allah.',
      bs: 'Sva hvala Allahu.',
    },
    reference: 'Muslim 597',
    repeat: 33,
  },
  {
    id: 'morning-6',
    categoryId: 'morning',
    arabic: 'اللَّهُ أَكْبَرُ',
    transliteration: 'Allahu Akbar',
    translation: {
      en: 'Allah is the Greatest.',
      bs: 'Allah je Najveći.',
    },
    reference: 'Muslim 597',
    repeat: 34,
  },
  {
    id: 'morning-7',
    categoryId: 'morning',
    arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    transliteration: 'Bismillahil-ladhi la yadurru ma\'asmihi shay\'un fil-ardi wa la fis-sama\'i wa huwas-sami\'ul-\'alim.',
    translation: {
      en: 'In the name of Allah with whose name nothing is harmed on earth nor in the heavens, and He is the All-Hearing, the All-Knowing.',
      bs: 'U ime Allaha — s Čijim imenom ništa na zemlji ni na nebu ne može nauditi — a On je Svečujni, Sveznajući.',
    },
    reference: 'Tirmidhi 3388 · Sahih',
    repeat: 3,
    virtue: {
      en: 'Whoever says it three times in the morning will not be afflicted by any sudden calamity until evening.',
      bs: 'Ko to tri puta izgovori ujutro neće ga zadesiti iznenadna nesreća do večeri.',
    },
  },
  {
    id: 'morning-8',
    categoryId: 'morning',
    arabic: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا',
    transliteration: 'Raditu billahi rabban, wa bil-Islami dinan, wa bi Muhammadin ﷺ nabiyyan.',
    translation: {
      en: 'I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad ﷺ as my Prophet.',
      bs: 'Zadovoljan sam Allahu kao Gospodarom, islamom kao vjerom i Muhammedom ﷺ kao vjerovjesnikom.',
    },
    reference: 'Tirmidhi 3389 · Hasan Sahih',
    repeat: 3,
  },
  {
    id: 'morning-9',
    categoryId: 'morning',
    arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ',
    transliteration: 'Qul huwallahu ahad. Allahus-samad. Lam yalid wa lam yulad. Wa lam yakun lahu kufuwan ahad.',
    translation: {
      en: 'Surah Al-Ikhlas — Say: He is Allah, the One...',
      bs: 'Sure El-Ihlas — Reci: On je Allah, Jedini...',
    },
    reference: 'Abu Dawud 5082 · Sahih',
    repeat: 3,
  },
  {
    id: 'morning-10',
    categoryId: 'morning',
    arabic: 'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِنْ شَرِّ مَا خَلَقَ',
    transliteration: 'Qul a\'udhu bi rabbil-falaq. Min sharri ma khalaq.',
    translation: {
      en: 'Surah Al-Falaq — Say: I seek refuge in the Lord of daybreak...',
      bs: 'Sure El-Felek — Reci: Tražim utočište u Gospodaru zore...',
    },
    reference: 'Abu Dawud 5082 · Sahih',
    repeat: 3,
  },
  {
    id: 'morning-11',
    categoryId: 'morning',
    arabic: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ',
    transliteration: 'Qul a\'udhu bi rabbin-nas. Malikin-nas.',
    translation: {
      en: 'Surah An-Nas — Say: I seek refuge in the Lord of mankind...',
      bs: 'Sure En-Nas — Reci: Tražim utočište u Gospodaru ljudi...',
    },
    reference: 'Abu Dawud 5082 · Sahih',
    repeat: 3,
  },
  {
    id: 'morning-12',
    categoryId: 'morning',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    transliteration: 'A\'udhu bi kalimatillahit-tammati min sharri ma khalaq.',
    translation: {
      en: 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
      bs: 'Tražim utočište u savršenim Allaahovim riječima od zla onoga što je On stvorio.',
    },
    reference: 'Muslim 2708',
    repeat: 3,
  },
  {
    id: 'morning-13',
    categoryId: 'morning',
    arabic: 'اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لَا إِلَٰهَ إِلَّا أَنْتَ',
    transliteration: 'Allahumma \'afini fi badani, Allahumma \'afini fi sam\'i, Allahumma \'afini fi basari, la ilaha illa ant.',
    translation: {
      en: 'O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight. None has the right to be worshipped except You.',
      bs: 'Allahu moj, daj mi zdravlje u tijelu. Allahu moj, daj mi zdravlje u sluhu. Allahu moj, daj mi zdravlje u vidu. Nema boga osim Tebe.',
    },
    reference: 'Abu Dawud 5090 · Sahih',
    repeat: 3,
  },
  {
    id: 'morning-14',
    categoryId: 'morning',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا',
    transliteration: 'Allahumma inni as\'aluka \'ilman nafi\'an, wa rizqan tayyiban, wa \'amalan mutaqabbalan.',
    translation: {
      en: 'O Allah, I ask You for beneficial knowledge, good provision, and deeds that are accepted.',
      bs: 'Allahu moj, molim Te za korisno znanje, čist opskrbu i djela koja su prihvaćena.',
    },
    reference: 'Ibn Majah 925 · Hasan Sahih',
    repeat: 1,
  },
  {
    id: 'morning-15',
    categoryId: 'morning',
    arabic: 'اللَّهُمَّ فَاطِرَ السَّمَاوَاتِ وَالْأَرْضِ، عَالِمَ الْغَيْبِ وَالشَّهَادَةِ، رَبَّ كُلِّ شَيْءٍ وَمَلِيكَهُ، أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا أَنْتَ، أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي، وَمِنْ شَرِّ الشَّيْطَانِ وَشِرْكِهِ',
    transliteration: 'Allahumma fatiras-samawati wal-ard, \'alimal-ghaybi wash-shahadah, rabba kulli shay\'in wa malikah, ashhadu an la ilaha illa ant, a\'udhu bika min sharri nafsi, wa min sharri sh-shaytani wa shirkih.',
    translation: {
      en: 'O Allah, Creator of the heavens and the earth, Knower of the unseen and the seen, Lord and Sovereign of everything, I bear witness that none has the right to be worshipped except You. I seek refuge in You from the evil of my soul and from the evil of Satan and his shirk.',
      bs: 'Allahu moj, Stvoritelju nebesa i zemlje, Znalac skrivenog i vidljivog, Gospodaru i Vladaru svega, svjedočim da nema boga osim Tebe. Tražim utočište u Tebi od zla svoje duše i od zla šejtana i njegovog širka.',
    },
    reference: 'Tirmidhi 3392 · Sahih',
    repeat: 1,
  },
  {
    id: 'morning-16',
    categoryId: 'morning',
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
    transliteration: 'SubhanAllahi wa bihamdih.',
    translation: {
      en: 'Glory be to Allah and praise be to Him.',
      bs: 'Slava Allahu i hvala Njemu.',
    },
    reference: 'Muslim 2694',
    repeat: 100,
    virtue: {
      en: 'Whoever says it one hundred times in the morning and evening — none will come on the Day of Resurrection with anything better, except one who said the same or more.',
      bs: 'Ko to izgovori sto puta ujutro i navečer — niko neće doći na Sudnji dan s boljim, osim onaj ko je rekao isto ili više.',
    },
  },

  // ─── Evening ───────────────────────────────────────────────
  {
    id: 'evening-1',
    categoryId: 'evening',
    arabic: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ',
    transliteration: 'Amsayna wa amsal-mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la sharika lah.',
    translation: {
      en: 'We have reached the evening and at this very time all sovereignty belongs to Allah. All praise is for Allah. None has the right to be worshipped except Allah, alone, without partner.',
      bs: 'Došli smo do večeri i u ovo vrijeme sva vlast pripada Allahu. Sva hvala Allahu. Nema boga osim Allaha, Jednog, bez partnera.',
    },
    reference: 'Muslim 2723',
    repeat: 1,
  },
  {
    id: 'evening-2',
    categoryId: 'evening',
    arabic: 'اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ',
    transliteration: 'Allahumma bika amsayna, wa bika asbahna, wa bika nahya, wa bika namutu, wa ilaykal-masir.',
    translation: {
      en: 'O Allah, by You we enter the evening and by You we enter the morning, by You we live and by You we die, and to You is the final return.',
      bs: 'Allahu moj, Tebe se držimo navečer i ujutro, Tebom živimo i Tebom umiremo, i Tebi je povratak.',
    },
    reference: 'Tirmidhi 3391 · Sahih',
    repeat: 1,
  },
  {
    id: 'evening-3',
    categoryId: 'evening',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    transliteration: 'A\'udhu bi kalimatillahit-tammati min sharri ma khalaq.',
    translation: {
      en: 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
      bs: 'Tražim utočište u savršenim Allaahovim riječima od zla onoga što je On stvorio.',
    },
    reference: 'Muslim 2708',
    repeat: 3,
  },
  {
    id: 'evening-4',
    categoryId: 'evening',
    arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    transliteration: 'Bismillahil-ladhi la yadurru ma\'asmihi shay\'un fil-ardi wa la fis-sama\'i wa huwas-sami\'ul-\'alim.',
    translation: {
      en: 'In the name of Allah with whose name nothing is harmed on earth nor in the heavens, and He is the All-Hearing, the All-Knowing.',
      bs: 'U ime Allaha — s Čijim imenom ništa ne može nauditi — a On je Svečujni, Sveznajući.',
    },
    reference: 'Tirmidhi 3388 · Sahih',
    repeat: 3,
  },
  {
    id: 'evening-5',
    categoryId: 'evening',
    arabic: 'سُبْحَانَ اللَّهِ',
    transliteration: 'SubhanAllah',
    translation: { en: 'Glory be to Allah.', bs: 'Slava Allahu.' },
    reference: 'Muslim 597',
    repeat: 33,
  },
  {
    id: 'evening-6',
    categoryId: 'evening',
    arabic: 'الْحَمْدُ لِلَّهِ',
    transliteration: 'Alhamdulillah',
    translation: { en: 'All praise is for Allah.', bs: 'Sva hvala Allahu.' },
    reference: 'Muslim 597',
    repeat: 33,
  },
  {
    id: 'evening-7',
    categoryId: 'evening',
    arabic: 'اللَّهُ أَكْبَرُ',
    transliteration: 'Allahu Akbar',
    translation: { en: 'Allah is the Greatest.', bs: 'Allah je Najveći.' },
    reference: 'Muslim 597',
    repeat: 34,
  },
  {
    id: 'evening-8',
    categoryId: 'evening',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: 'Allahumma anta rabbi la ilaha illa ant, khalaqtani wa ana \'abduk, wa ana \'ala \'ahdika wa wa\'dika mastata\'t, a\'udhu bika min sharri ma sana\'t, abu\'u laka bi ni\'matika \'alayya, wa abu\'u bi dhanbi faghfir li fa innahu la yaghfirudh-dhunuba illa ant.',
    translation: {
      en: 'Sayyid al-Istighfar: O Allah, You are my Lord. None has the right to be worshipped except You. You created me and I am Your servant. I abide by Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favour upon me and I acknowledge my sin, so forgive me, for none forgives sins except You.',
      bs: 'Gospodarski istigfar: Allahu moj, Ti si moj Gospodar. Nema boga osim Tebe. Ti si me stvorio i ja sam Tvoj rob. Držim se Tvog saveza i obećanja koliko mogu. Tražim utočište u Tebi od zla onoga što sam učinio. Priznajem Tvoju blagodat prema meni i priznajem svoj grijeh, pa mi oprosti, jer niko ne oprašta grijehe osim Tebe.',
    },
    reference: 'Bukhari 6306',
    repeat: 1,
    virtue: {
      en: 'Whoever says it with certainty in the evening and dies that night enters Paradise.',
      bs: 'Ko to izgovori navečer s uvjerenjem i umre te noći — ući će u Džennet.',
    },
  },
  {
    id: 'evening-9',
    categoryId: 'evening',
    arabic: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا',
    transliteration: 'Raditu billahi rabban, wa bil-Islami dinan, wa bi Muhammadin ﷺ nabiyyan.',
    translation: {
      en: 'I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad ﷺ as my Prophet.',
      bs: 'Zadovoljan sam Allahu kao Gospodarom, islamom kao vjerom i Muhammedom ﷺ kao vjerovjesnikom.',
    },
    reference: 'Tirmidhi 3389 · Hasan Sahih',
    repeat: 3,
  },
  {
    id: 'evening-10',
    categoryId: 'evening',
    arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ',
    transliteration: 'Qul huwallahu ahad. Allahus-samad. Lam yalid wa lam yulad. Wa lam yakun lahu kufuwan ahad.',
    translation: {
      en: 'Surah Al-Ikhlas — Say: He is Allah, the One...',
      bs: 'Sure El-Ihlas — Reci: On je Allah, Jedini...',
    },
    reference: 'Abu Dawud 5082 · Sahih',
    repeat: 3,
  },
  {
    id: 'evening-11',
    categoryId: 'evening',
    arabic: 'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِنْ شَرِّ مَا خَلَقَ',
    transliteration: 'Qul a\'udhu bi rabbil-falaq. Min sharri ma khalaq.',
    translation: {
      en: 'Surah Al-Falaq — Say: I seek refuge in the Lord of daybreak...',
      bs: 'Sure El-Felek — Reci: Tražim utočište u Gospodaru zore...',
    },
    reference: 'Abu Dawud 5082 · Sahih',
    repeat: 3,
  },
  {
    id: 'evening-12',
    categoryId: 'evening',
    arabic: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ',
    transliteration: 'Qul a\'udhu bi rabbin-nas. Malikin-nas.',
    translation: {
      en: 'Surah An-Nas — Say: I seek refuge in the Lord of mankind...',
      bs: 'Sure En-Nas — Reci: Tražim utočište u Gospodaru ljudi...',
    },
    reference: 'Abu Dawud 5082 · Sahih',
    repeat: 3,
  },
  {
    id: 'evening-13',
    categoryId: 'evening',
    arabic: 'اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لَا إِلَٰهَ إِلَّا أَنْتَ',
    transliteration: 'Allahumma \'afini fi badani, Allahumma \'afini fi sam\'i, Allahumma \'afini fi basari, la ilaha illa ant.',
    translation: {
      en: 'O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight. None has the right to be worshipped except You.',
      bs: 'Allahu moj, daj mi zdravlje u tijelu. Allahu moj, daj mi zdravlje u sluhu. Allahu moj, daj mi zdravlje u vidu. Nema boga osim Tebe.',
    },
    reference: 'Abu Dawud 5090 · Sahih',
    repeat: 3,
  },

  // ─── Before sleep ──────────────────────────────────────────
  {
    id: 'sleep-1',
    categoryId: 'sleep',
    arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    transliteration: 'Bismika Allahumma amutu wa ahya.',
    translation: {
      en: 'In Your name, O Allah, I die and I live.',
      bs: 'U Tvom imenu, Allahu moj, umirem i živim.',
    },
    reference: 'Bukhari 6324',
    repeat: 1,
  },
  {
    id: 'sleep-2',
    categoryId: 'sleep',
    arabic: 'اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ',
    transliteration: 'Allahumma qini \'adhabaka yawma tab\'athu \'ibadak.',
    translation: {
      en: 'O Allah, protect me from Your punishment on the Day You resurrect Your servants.',
      bs: 'Allahu moj, sačuvaj me od Svoje kazne na Dan kada uskrisiš Svoje robove.',
    },
    reference: 'Tirmidhi 3398 · Sahih',
    repeat: 3,
  },
  {
    id: 'sleep-3',
    categoryId: 'sleep',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا، وَكَفَانَا، وَآوَانَا، فَكَمْ مِمَّنْ لَا كَافِيَ لَهُ وَلَا مُؤْوِيَ',
    transliteration: 'Alhamdu lillahil-ladhi at\'amana wa saqana, wa kafana, wa awana, fakam mimman la kafiya lahu wa la mu\'wiya.',
    translation: {
      en: 'All praise is for Allah who fed us, gave us drink, sufficed us and gave us shelter. How many have none to suffice them or shelter them.',
      bs: 'Hvala Allahu koji nas je nahranio, napojio, zadovoljio i dao nam sklonište. Koliko ih nema ko da ih zadovolji ili primi.',
    },
    reference: 'Muslim 2715',
    repeat: 1,
  },
  {
    id: 'sleep-4',
    categoryId: 'sleep',
    arabic: 'اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ، وَفَوَّضْتُ أَمْرِي إِلَيْكَ، وَوَجَّهْتُ وَجْهِي إِلَيْكَ، وَأَلْجَأْتُ ظَهْرِي إِلَيْكَ، رَغْبَةً وَرَهْبَةً إِلَيْكَ، لَا مَلْجَأَ وَلَا مَنْجَا مِنْكَ إِلَّا إِلَيْكَ، آمَنْتُ بِكِتَابِكَ الَّذِي أَنْزَلْتَ، وَنَبِيِّكَ الَّذِي أَرْسَلْتَ',
    transliteration: 'Allahumma aslamtu nafsi ilayk, wa fawwadtu amri ilayk, wa wajjahtu wajhi ilayk, wa alja\'tu dhahri ilayk, raghbatan wa rahbatan ilayk, la malja\'a wa la manja minka illa ilayk, amantu bi kitabikal-ladhi anzalta, wa nabiyyikal-ladhi arsalta.',
    translation: {
      en: 'O Allah, I submit my soul to You, entrust my affair to You, turn my face to You, and rely on You in hope and fear of You. There is no refuge nor escape from You except to You. I believe in Your Book which You revealed and in Your Prophet whom You sent.',
      bs: 'Allahu moj, predajem Ti dušu, prepustam Ti svoje stvari, okrećem Ti lice i oslanjam se na Tebe u nadi i strahu. Nema utočišta ni spasenja od Tebe osim kod Tebe. Vjerujem u Tvoju Knjigu i Tvog poslanika.',
    },
    reference: 'Bukhari 6311 · Muslim 2710',
    repeat: 1,
    virtue: {
      en: 'If you die that night, you die upon the fitrah. Make this your last words.',
      bs: 'Ako umrete te noći, umirete na fitri. Neka ovo budu posljednje riječi.',
    },
  },
  {
    id: 'sleep-5',
    categoryId: 'sleep',
    arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ',
    transliteration: 'Qul huwallahu ahad... (Al-Ikhlas, Al-Falaq, An-Nas — each once)',
    translation: {
      en: 'Recite Al-Ikhlas, Al-Falaq and An-Nas, then blow into your palms and wipe over your body.',
      bs: 'Pročitaj El-Ihlas, El-Felek i En-Nas, pa dumni u dlanove i pređi preko tijela.',
    },
    reference: 'Bukhari 5017',
    repeat: 1,
  },
  {
    id: 'sleep-6',
    categoryId: 'sleep',
    arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ',
    transliteration: 'Allahu la ilaha illa huwal-Hayyul-Qayyum, la ta\'khudhuhu sinatun wa la nawm, lahu ma fis-samawati wa ma fil-ard... (Ayat al-Kursi, Al-Baqarah 2:255)',
    translation: {
      en: 'Recite Ayat al-Kursi (Al-Baqarah 2:255) before sleeping — Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence...',
      bs: 'Pročitaj Ajetul-Kursi (El-Bekara 2:255) prije spavanja — Allah — nema boga osim Njega, Živog, Održavaoca postojanja...',
    },
    reference: 'Bukhari 2311',
    repeat: 1,
    virtue: {
      en: 'A protector from Allah remains over you and no devil approaches you until morning.',
      bs: 'Allahov zaštitnik ostaje nad tobom i nijedan šejtan ti ne prilazi do jutra.',
    },
  },
  {
    id: 'sleep-7',
    categoryId: 'sleep',
    arabic: 'آمَنَ الرَّسُولُ بِمَا أُنْزِلَ إِلَيْهِ مِنْ رَبِّهِ وَالْمُؤْمِنُونَ ۚ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ',
    transliteration: 'Amanar-rasulu bima unzila ilayhi min rabbihi wal-mu\'minun... (Last two ayahs of Al-Baqarah, 2:285–286)',
    translation: {
      en: 'Recite the last two ayahs of Surah Al-Baqarah (2:285–286). The Messenger believed in what was revealed to him from his Lord, and so did the believers...',
      bs: 'Pročitaj posljednja dva ajeta Sure El-Bekara (2:285–286). Poslanik vjeruje u ono što mu je objavljeno od Gospodara, i vjernici...',
    },
    reference: 'Bukhari 5003 · Muslim 807',
    repeat: 1,
    virtue: {
      en: 'These two ayahs suffice whoever recites them at night.',
      bs: 'Ova dva ajeta dovoljna su onome ko ih pročita noću.',
    },
  },
  {
    id: 'sleep-8',
    categoryId: 'sleep',
    arabic: 'اللَّهُمَّ إِنَّكَ خَلَقْتَ نَفْسِي وَأَنْتَ تَوَفَّاهَا، لَكَ مَمَاتُهَا وَمَحْيَاهَا، إِنْ أَحْيَيْتَهَا فَاحْفَظْهَا، وَإِنْ أَمَتَّهَا فَاغْفِرْ لَهَا',
    transliteration: 'Allahumma innaka khalaqta nafsi wa anta tawaffaha, laka mamatuha wa mahyaha, in ahyaytaha fahfazha, wa amattaha faghfir laha.',
    translation: {
      en: 'O Allah, You created my soul and You take it back. Yours is its death and its life. If You give it life, protect it; and if You cause it to die, forgive it.',
      bs: 'Allahu moj, Ti si stvorio moju dušu i Ti je uzimaš. Tvoja je njena smrt i život. Ako je oživiš — sačuvaj je; a ako je usmrtiš — oprosti joj.',
    },
    reference: 'Muslim 2712',
    repeat: 1,
  },

  // ─── Upon waking ───────────────────────────────────────────
  {
    id: 'waking-1',
    categoryId: 'waking',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    transliteration: 'Alhamdu lillahil-ladhi ahyana ba\'da ma amatana wa ilayhin-nushur.',
    translation: {
      en: 'All praise is for Allah who gave us life after causing us to die, and to Him is the resurrection.',
      bs: 'Hvala Allahu koji nas je oživio poslije smrti, i Njemu je uskrsnuće.',
    },
    reference: 'Bukhari 6312',
    repeat: 1,
  },
  {
    id: 'waking-2',
    categoryId: 'waking',
    arabic: 'لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ، سُبْحَانَ اللَّهِ، وَالْحَمْدُ لِلَّهِ، وَلَا إِلَٰهَ إِلَّا اللَّهُ، وَاللَّهُ أَكْبَرُ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: 'La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu, wa huwa \'ala kulli shay\'in qadir. SubhanAllah, walhamdulillah, wa la ilaha illallah, wallahu akbar, wa la hawla wa la quwwata illa billah.',
    translation: {
      en: 'None has the right to be worshipped except Allah, alone... then: Glory be to Allah, all praise is for Allah, none has the right to be worshipped except Allah, Allah is the Greatest, and there is no power nor might except with Allah.',
      bs: 'Nema boga osim Allaha, Jednog... zatim: Slava Allahu, hvala Allahu, nema boga osim Allaha, Allah je Najveći, nema snage ni moći osim u Allahu.',
    },
    reference: 'Bukhari 6312',
    repeat: 1,
  },
  {
    id: 'waking-3',
    categoryId: 'waking',
    arabic: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ',
    transliteration: 'Allahumma bika asbahna, wa bika amsayna, wa bika nahya, wa bika namutu, wa ilaykan-nushur.',
    translation: {
      en: 'O Allah, by You we enter the morning and by You we enter the evening, by You we live and by You we die, and to You is the resurrection.',
      bs: 'Allahu moj, Tebe se držimo ujutro i navečer, Tebom živimo i Tebom umiremo, i Tebi je povratak.',
    },
    reference: 'Tirmidhi 3391 · Sahih',
    repeat: 1,
  },
  {
    id: 'waking-4',
    categoryId: 'waking',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي عَافَانِي فِيمَا ابْتَلَىٰ كَثِيرًا مِنْ خَلْقِهِ بِالْمَرَضِ وَالْعَمَىٰ وَالْبُرَسِ',
    transliteration: 'Alhamdu lillahil-ladhi \'afani fima ibtala kathiran min khalqihi bil-maradi wal-\'ama wal-burs.',
    translation: {
      en: 'All praise is for Allah who granted me health in what afflicted many of His creation with sickness, blindness, and leprosy.',
      bs: 'Hvala Allahu koji mi je dao zdravlje u onome u čemu je mnoge od Svog stvorenja zadesila bolest, sljepoća i guba.',
    },
    reference: 'Tirmidhi 3457 · Hasan Sahih',
    repeat: 1,
  },

  // ─── Protection ────────────────────────────────────────────
  {
    id: 'protection-1',
    categoryId: 'protection',
    arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    transliteration: 'Allahu la ilaha illa huwal-Hayyul-Qayyum, la ta\'khudhuhu sinatun wa la nawm, lahu ma fis-samawati wa ma fil-ard... (Ayat al-Kursi, Al-Baqarah 2:255)',
    translation: {
      en: 'Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence... (full Ayat al-Kursi, Al-Baqarah 2:255)',
      bs: 'Allah — nema boga osim Njega, Živog, Održavaoca postojanja... (cijela Ajetul-Kursi, El-Bekara 2:255)',
    },
    reference: 'Bukhari 2311 · Muslim 810',
    repeat: 1,
    virtue: {
      en: 'Whoever recites it in the morning is protected until evening; in the evening until morning.',
      bs: 'Ko je pročita ujutro — zaštićen je do večeri; navečer — do jutra.',
    },
  },
  {
    id: 'protection-2',
    categoryId: 'protection',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    transliteration: 'A\'udhu bi kalimatillahit-tammati min sharri ma khalaq.',
    translation: {
      en: 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
      bs: 'Tražim utočište u savršenim Allaahovim riječima od zla onoga što je stvorio.',
    },
    reference: 'Muslim 2708',
    repeat: 3,
  },
  {
    id: 'protection-3',
    categoryId: 'protection',
    arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    transliteration: 'Bismillahil-ladhi la yadurru ma\'asmihi shay\'un...',
    translation: {
      en: 'In the name of Allah with whose name nothing is harmed on earth nor in the heavens.',
      bs: 'U ime Allaha s Čijim imenom ništa ne može nauditi.',
    },
    reference: 'Tirmidhi 3388 · Sahih',
    repeat: 3,
  },
  {
    id: 'protection-4',
    categoryId: 'protection',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ، وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ',
    transliteration: 'A\'udhu bi kalimatillahit-tammati min kulli shaytanin wa hammah, wa min kulli \'aynin lammah.',
    translation: {
      en: 'I seek refuge in the perfect words of Allah from every devil and poisonous creature, and from every envious evil eye.',
      bs: 'Tražim utočište u savršenim Allaahovim riječima od svakog šejtana i otrovnog stvorenja, i od zavidnog oka.',
    },
    reference: 'Bukhari 3371',
    repeat: 1,
  },
  {
    id: 'protection-5',
    categoryId: 'protection',
    arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ',
    transliteration: 'Qul huwallahu ahad... (Al-Ikhlas, Al-Falaq, An-Nas — recite, blow into palms, wipe over body)',
    translation: {
      en: 'For ruqyah: recite Al-Ikhlas, Al-Falaq and An-Nas, then blow into your palms and wipe over your body.',
      bs: 'Za ruqju: pročitaj El-Ihlas, El-Felek i En-Nas, pa dumni u dlanove i pređi preko tijela.',
    },
    reference: 'Bukhari 5016',
    repeat: 3,
  },
  {
    id: 'protection-6',
    categoryId: 'protection',
    arabic: 'حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ ۖ عَلَيْهِ تَوَكَّلْتُ ۖ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
    transliteration: 'Hasbiyallahu la ilaha illa huwa, \'alayhi tawakkaltu, wa huwa rabbul-\'arshil-\'azim.',
    translation: {
      en: 'Allah is sufficient for me. None has the right to be worshipped except Him. I have placed my trust in Him, and He is the Lord of the Magnificent Throne.',
      bs: 'Dovoljan mi je Allah. Nema boga osim Njega. Na Njega se oslanjam i On je Gospodar Veličanstvenog Arša.',
    },
    reference: 'Abu Dawud 5095 · Hasan Sahih',
    repeat: 7,
    virtue: {
      en: 'Allah will suffice whoever says it seven times against whatever grieves him.',
      bs: 'Allah će dovoljiti onome ko to sedam puta izgovori protiv onoga što ga muči.',
    },
  },

  // ─── After prayer ────────────────────────────────────────────
  {
    id: 'after-1',
    categoryId: 'after-prayer',
    arabic: 'أَسْتَغْفِرُ اللَّهَ',
    transliteration: 'Astaghfirullah',
    translation: {
      en: 'I seek forgiveness from Allah.',
      bs: 'Tražim oprost od Allaha.',
    },
    reference: 'Muslim 591',
    repeat: 3,
  },
  {
    id: 'after-2',
    categoryId: 'after-prayer',
    arabic: 'اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ',
    transliteration: 'Allahumma antas-salam wa minkas-salam, tabarakta ya dhal-jalali wal-ikram.',
    translation: {
      en: 'O Allah, You are As-Salam and from You is all peace. Blessed are You, O Owner of majesty and honour.',
      bs: 'Allahu moj, Ti si Mir i od Tebe je mir. Blagosloven si, o Gospodaru veličine i časti.',
    },
    reference: 'Muslim 591',
    repeat: 1,
  },
  {
    id: 'after-3',
    categoryId: 'after-prayer',
    arabic: 'لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa \'ala kulli shay\'in qadir.',
    translation: {
      en: 'None has the right to be worshipped except Allah, alone, without partner. To Him belongs all sovereignty and praise and He is over all things omnipotent.',
      bs: 'Nema boga osim Allaha, Jednog, bez partnera. Njemu pripada vlast i hvala i On je nad svim stvarima Svemoćan.',
    },
    reference: 'Muslim 597',
    repeat: 33,
  },
  {
    id: 'after-4',
    categoryId: 'after-prayer',
    arabic: 'سُبْحَانَ اللَّهِ',
    transliteration: 'SubhanAllah',
    translation: { en: 'Glory be to Allah.', bs: 'Slava Allahu.' },
    reference: 'Bukhari 843 · Muslim 594',
    repeat: 33,
  },
  {
    id: 'after-5',
    categoryId: 'after-prayer',
    arabic: 'الْحَمْدُ لِلَّهِ',
    transliteration: 'Alhamdulillah',
    translation: { en: 'All praise is for Allah.', bs: 'Sva hvala Allahu.' },
    reference: 'Bukhari 843 · Muslim 594',
    repeat: 33,
  },
  {
    id: 'after-6',
    categoryId: 'after-prayer',
    arabic: 'اللَّهُ أَكْبَرُ',
    transliteration: 'Allahu Akbar',
    translation: { en: 'Allah is the Greatest.', bs: 'Allah je Najveći.' },
    reference: 'Bukhari 843 · Muslim 594',
    repeat: 34,
  },
  {
    id: 'after-7',
    categoryId: 'after-prayer',
    arabic: 'اللَّهُمَّ أَعِنِّي عَلَىٰ ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ',
    transliteration: 'Allahumma a\'inni \'ala dhikrika wa shukrika wa husni \'ibadatik.',
    translation: {
      en: 'O Allah, help me to remember You, to thank You, and to worship You in the best manner.',
      bs: 'Allahu moj, pomozi mi da Te spominjem, da Ti zahvaljujem i da Te najljepše ibadetujem.',
    },
    reference: 'Abu Dawud 1522 · Sahih',
    repeat: 1,
  },
  {
    id: 'after-8',
    categoryId: 'after-prayer',
    arabic: 'لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa \'ala kulli shay\'in qadir.',
    translation: {
      en: 'None has the right to be worshipped except Allah, alone, without partner. To Him belongs all sovereignty and praise and He is over all things omnipotent. (Once after each obligatory prayer)',
      bs: 'Nema boga osim Allaha, Jednog, bez partnera. Njemu pripada vlast i hvala i On je nad svim stvarima Svemoćan. (Jednom poslije svakog farz namaza)',
    },
    reference: 'Bukhari 844 · Muslim 269',
    repeat: 1,
    virtue: {
      en: 'Ten good deeds are recorded, ten sins erased, and he is raised ten degrees.',
      bs: 'Zapisuje se deset dobročinstava, briše deset grijeha i podiže se za deset stepeni.',
    },
  },
  {
    id: 'after-9',
    categoryId: 'after-prayer',
    arabic: 'اللَّهُمَّ لَا مَانِعَ لِمَا أَعْطَيْتَ، وَلَا مُعْطِيَ لِمَا مَنَعْتَ، وَلَا يَنْفَعُ ذَا الْجَدِّ مِنْكَ الْجَدُّ',
    transliteration: 'Allahumma la mani\'a lima a\'tayta, wa la mu\'tiya lima mana\'ta, wa la yanfa\'u dhal-jaddi minkal-jadd.',
    translation: {
      en: 'O Allah, none can withhold what You give, none can give what You withhold, and no wealth or might avails against You.',
      bs: 'Allahu moj, niko ne može spriječiti ono što Ti daš, niko ne može dati ono što Ti uskratiš, i bogatstvo ne pomaže protiv Tebe.',
    },
    reference: 'Bukhari 844 · Muslim 593',
    repeat: 1,
  },

  // ─── General ───────────────────────────────────────────────
  {
    id: 'general-1',
    categoryId: 'general',
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
    transliteration: 'SubhanAllahi wa bihamdih.',
    translation: {
      en: 'Glory be to Allah and praise be to Him.',
      bs: 'Slava Allahu i hvala Njemu.',
    },
    reference: 'Bukhari 6405 · Muslim 2694',
    repeat: 100,
    virtue: {
      en: 'Sins are forgiven even if like the foam of the sea.',
      bs: 'Grijehovi se opraštaju, makar bili kao pjena mora.',
    },
  },
  {
    id: 'general-2',
    categoryId: 'general',
    arabic: 'لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa \'ala kulli shay\'in qadir.',
    translation: {
      en: 'None has the right to be worshipped except Allah, alone, without partner...',
      bs: 'Nema boga osim Allaha, Jednog, bez partnera...',
    },
    reference: 'Bukhari 3293 · Muslim 2691',
    repeat: 10,
    virtue: {
      en: 'Like freeing four slaves from the children of Ismail.',
      bs: 'Nagrada kao oslobođenje četiri roba iz djece Ismaila.',
    },
  },
  {
    id: 'general-3',
    categoryId: 'general',
    arabic: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: 'La hawla wa la quwwata illa billah.',
    translation: {
      en: 'There is no power nor might except with Allah.',
      bs: 'Nema snage ni moći osim u Allahu.',
    },
    reference: 'Bukhari 6384 · Muslim 2705',
    repeat: 1,
    virtue: {
      en: 'A treasure from the treasures of Paradise.',
      bs: 'Blago iz blaga Dženneta.',
    },
  },
  {
    id: 'general-4',
    categoryId: 'general',
    arabic: 'سُبْحَانَ اللَّهِ الْعَظِيمِ وَبِحَمْدِهِ',
    transliteration: 'SubhanAllahil-\'Azim wa bihamdih.',
    translation: {
      en: 'Glory be to Allah, the Magnificent, and praise be to Him.',
      bs: 'Slava Allahu Veličanstvenom i hvala Njemu.',
    },
    reference: 'Bukhari 6682 · Muslim 2694',
    repeat: 1,
    virtue: {
      en: 'A date palm is planted for him in Paradise.',
      bs: 'Zasadi mu se palma u Džennetu.',
    },
  },
  {
    id: 'general-5',
    categoryId: 'general',
    arabic: 'اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ',
    transliteration: 'Allahumma salli \'ala Muhammadin wa \'ala ali Muhammad, kama sallayta \'ala Ibrahima wa \'ala ali Ibrahim, innaka Hamidun Majid.',
    translation: {
      en: 'O Allah, send blessings upon Muhammad and upon the family of Muhammad, as You sent blessings upon Ibrahim and upon the family of Ibrahim. Indeed, You are Praiseworthy, Glorious.',
      bs: 'Allahu moj, blagoslovi Muhammeda i porodicu Muhammeda, kao što si blagoslovio Ibrahim i porodicu Ibrahimovu. Zaista si Hvaljeni, Veličanstveni.',
    },
    reference: 'Bukhari 3370 · Muslim 406',
    repeat: 10,
    virtue: {
      en: 'Whoever sends blessings upon me once, Allah sends blessings upon him ten times.',
      bs: 'Ko jednom pošalje salavat na mene, Allah mu pošalje deset salavata.',
    },
  },
  {
    id: 'general-6',
    categoryId: 'general',
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ',
    transliteration: 'SubhanAllahi wa bihamdih, SubhanAllahil-\'Azim.',
    translation: {
      en: 'Glory be to Allah and praise be to Him. Glory be to Allah, the Magnificent.',
      bs: 'Slava Allahu i hvala Njemu. Slava Allahu Veličanstvenom.',
    },
    reference: 'Bukhari 6406 · Muslim 2694',
    repeat: 100,
    virtue: {
      en: 'Two words light on the tongue, heavy on the scales, beloved to the Most Merciful.',
      bs: 'Dvije riječi lake na jeziku, teške na vagi, omiljene Milostivom.',
    },
  },
  {
    id: 'general-7',
    categoryId: 'general',
    arabic: 'أَسْتَغْفِرُ اللَّهَ',
    transliteration: 'Astaghfirullah.',
    translation: {
      en: 'I seek forgiveness from Allah.',
      bs: 'Tražim oprost od Allaha.',
    },
    reference: 'Muslim 2702',
    repeat: 100,
    virtue: {
      en: 'The Prophet ﷺ sought forgiveness from Allah more than one hundred times daily.',
      bs: 'Poslanik ﷺ tražio je oprost od Allaha više od stotinu puta dnevno.',
    },
  },
  {
    id: 'general-8',
    categoryId: 'general',
    arabic: 'سُبْحَانَ اللَّهِ، وَالْحَمْدُ لِلَّهِ، وَلَا إِلَٰهَ إِلَّا اللَّهُ، وَاللَّهُ أَكْبَرُ',
    transliteration: 'SubhanAllah, walhamdulillah, wa la ilaha illallah, wallahu akbar.',
    translation: {
      en: 'Glory be to Allah. All praise is for Allah. None has the right to be worshipped except Allah. Allah is the Greatest.',
      bs: 'Slava Allahu. Sva hvala Allahu. Nema boga osim Allaha. Allah je Najveći.',
    },
    reference: 'Muslim 2137',
    repeat: 1,
    virtue: {
      en: 'These words are more beloved to the Prophet ﷺ than everything the sun rises upon.',
      bs: 'Ove riječi su omiljenije Poslaniku ﷺ od svega na čemu sunce izlazi.',
    },
  },
  {
    id: 'general-9',
    categoryId: 'general',
    arabic: 'لَا إِلَٰهَ إِلَّا اللَّهُ، وَاللَّهُ أَكْبَرُ',
    transliteration: 'La ilaha illallah, wallahu akbar.',
    translation: {
      en: 'None has the right to be worshipped except Allah, and Allah is the Greatest.',
      bs: 'Nema boga osim Allaha, a Allah je Najveći.',
    },
    reference: 'Muslim 2137',
    repeat: 1,
    virtue: {
      en: 'The best remembrance after the Book of Allah.',
      bs: 'Najbolji zikr poslije Allaahove Knjige.',
    },
  },

  // ─── Distress ───────────────────────────────────────────────
  {
    id: 'distress-1',
    categoryId: 'distress',
    arabic: 'لَا إِلَٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ',
    transliteration: 'La ilaha illa anta subhanaka inni kuntu minadh-dhalimin.',
    translation: {
      en: 'Dua of Yunus (as): None has the right to be worshipped except You, glory be to You. Indeed, I have been of the wrongdoers.',
      bs: 'Dova Junusovog (a.s.): Nema boga osim Tebe, slava Tebi. Zaista sam bio među nepravednima.',
    },
    reference: 'Tirmidhi 3505 · Sahih',
    repeat: 1,
    virtue: {
      en: 'No Muslim supplicates with it except Allah answers him.',
      bs: 'Nijedan musliman ne zazove ovim a da Allah ne odgovori.',
    },
  },
  {
    id: 'distress-2',
    categoryId: 'distress',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ، وَأَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ وَقَهْرِ الرِّجَالِ',
    transliteration: 'Allahumma inni a\'udhu bika minal-hammi wal-hazan, wa a\'udhu bika minal-\'ajzi wal-kasal, wa a\'udhu bika minal-jubni wal-bukhl, wa a\'udhu bika min ghalabatid-dayni wa qahrir-rijal.',
    translation: {
      en: 'O Allah, I seek refuge in You from anxiety and grief, from incapacity and laziness, from cowardice and miserliness, and from being overpowered by debt and men.',
      bs: 'Allahu moj, tražim utočište u Tebi od tjeskobe i tuge, od nemoći i lijenosti, od kukavičluka i škrtosti, i od pritiska duga i ljudi.',
    },
    reference: 'Bukhari 6369',
    repeat: 1,
  },
  {
    id: 'distress-3',
    categoryId: 'distress',
    arabic: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ',
    transliteration: 'Hasbunallahu wa ni\'mal-wakil.',
    translation: {
      en: 'Allah is sufficient for us, and He is the best Disposer of affairs.',
      bs: 'Dovoljan nam je Allah i On je najbolji Zaštitnik.',
    },
    reference: 'Bukhari 3818 · Quran 3:173',
    repeat: 1,
  },
  {
    id: 'distress-4',
    categoryId: 'distress',
    arabic: 'اللَّهُمَّ رَحْمَتَكَ أَرْجُو فَلَا تَكِلْنِي إِلَىٰ نَفْسِي طَرْفَةَ عَيْنٍ، وَأَصْلِحْ لِي شَأْنِي كُلَّهُ، لَا إِلَٰهَ إِلَّا أَنْتَ',
    transliteration: 'Allahumma rahmataka arju fala takilni ila nafsi tarfata \'ayn, wa aslih li sha\'ni kullahu, la ilaha illa ant.',
    translation: {
      en: 'O Allah, I hope for Your mercy. Do not leave me to myself even for the blink of an eye. Set right all my affairs. None has the right to be worshipped except You.',
      bs: 'Allahu moj, nadam se Tvojoj milosti. Ne prepustaj me samom sebi ni tren oka. Uredi mi sve stvari. Nema boga osim Tebe.',
    },
    reference: 'Abu Dawud 5090 · Sahih',
    repeat: 1,
  },

  // ─── Distress (continued) ───────────────────────────────────
  {
    id: 'distress-5',
    categoryId: 'distress',
    arabic: 'إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ',
    transliteration: 'Inna lillahi wa inna ilayhi raji\'un.',
    translation: {
      en: 'Indeed, we belong to Allah and indeed to Him we will return. (Upon hearing of a calamity or loss)',
      bs: 'Mi pripadamo Allahu i Njemu se vraćamo. (Kad doživite nesreću ili gubitak)',
    },
    reference: 'Muslim 918 · Quran 2:156',
    repeat: 1,
  },
  {
    id: 'distress-6',
    categoryId: 'distress',
    arabic: 'اللَّهُمَّ إِنِّي عَبْدُكَ، ابْنُ عَبْدِكَ، ابْنُ أَمَتِكَ، نَاصِيَتِي بِيَدِكَ، مَاضٍ فِيَّ حُكْمُكَ، عَدْلٌ فِيَّ قَضَاؤُكَ، أَسْأَلُكَ بِكُلِّ اسْمٍ هُوَ لَكَ، سَمَّيْتَ بِهِ نَفْسَكَ، أَوْ أَنْزَلْتَهُ فِي كِتَابِكَ، أَوْ عَلَّمْتَهُ أَحَدًا مِنْ خَلْقِكَ، أَوِ اسْتَأْثَرْتَ بِهِ فِي عِلْمِ الْغَيْبِ عِنْدَكَ، أَنْ تَجْعَلَ الْقُرْآنَ رَبِيعَ قَلْبِي، وَنُورَ صَدْرِي، وَجَلَاءَ حُزْنِي، وَذَهَابَ هَمِّي',
    transliteration: 'Allahumma inni \'abduk, ibnu \'abdik, ibnu amatik, nasiyati bi yadik, madin fiyya hukmuk, \'adlun fiyya qada\'uk... (Dua for anxiety)',
    translation: {
      en: 'O Allah, I am Your servant, son of Your servant, son of Your maidservant. My forelock is in Your hand, Your command over me is forever executed and Your decree over me is just. I ask You by every name belonging to You... that You make the Quran the spring of my heart, the light of my chest, the banisher of my grief and the reliever of my anxiety.',
      bs: 'Allahu moj, ja sam Tvoj rob, sin Tvog roba, sin Tvoje robinje. Moja prednja kosa je u Tvojoj ruci, Tvoja naredba nad mnom se izvršava i Tvoja presuda nad mnom je pravedna. Molim Te Svakim imenom koje pripada Tebi... da učiniš Kur\'an prolećem mog srca, svjetlošću moje grudi, uklanjanjem moje tuge i olakšanjem moje brige.',
    },
    reference: 'Ahmad 1/391 · Hasan Sahih',
    repeat: 1,
  },
  {
    id: 'distress-7',
    categoryId: 'distress',
    arabic: 'رَبِّ اشْرَحْ لِي صَدْرِي، وَيَسِّرْ لِي أَمْرِي، وَاحْلُلْ عُقْدَةً مِنْ لِسَانِي، يَفْقَهُوا قَوْلِي',
    transliteration: 'Rabbish-rah li sadri, wa yassir li amri, wahlul \'uqdatan min lisani, yafqahu qawli.',
    translation: {
      en: 'My Lord, expand for me my chest, ease for me my task, and untie the knot from my tongue that they may understand my speech. (Dua of Musa, peace be upon him)',
      bs: 'Gospodaru moj, proširi mi grudi, olakšaj mi moj posao i odveži čvor sa mog jezika da razumiju moj govor. (Dova Musa, a.s.)',
    },
    reference: 'Quran 20:25–28',
    repeat: 1,
  },

  // ─── Travel ────────────────────────────────────────────────
  {
    id: 'travel-1',
    categoryId: 'travel',
    arabic: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ، وَإِنَّا إِلَىٰ رَبِّنَا لَمُنْقَلِبُونَ',
    transliteration: 'Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrinin, wa inna ila rabbina lamunqalibun.',
    translation: {
      en: 'Glory be to Him who has subjected this to us, and we could never have it by our efforts. And to our Lord we will surely return.',
      bs: 'Slava Onome koji nam je ovo pokorio, a mi sami to nismo mogli. I našem Gospodaru se sigurno vraćamo.',
    },
    reference: 'Muslim 1342 · Quran 43:13-14',
    repeat: 1,
  },
  {
    id: 'travel-2',
    categoryId: 'travel',
    arabic: 'اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَٰذَا الْبِرَّ وَالتَّقْوَىٰ، وَمِنَ الْعَمَلِ مَا تَرْضَىٰ، اللَّهُمَّ هَوِّنْ عَلَيْنَا سَفَرَنَا هَٰذَا وَاطْوِ عَنَّا بُعْدَهُ',
    transliteration: 'Allahumma inna nas\'aluka fi safarina hadha al-birra wat-taqwa, wa minal-\'amali ma tardha. Allahumma hawwin \'alayna safarana hadha watwi \'anna bu\'dah.',
    translation: {
      en: 'O Allah, we ask You on this journey for righteousness and piety, and deeds that please You. O Allah, make this journey easy for us and shorten its distance for us.',
      bs: 'Allahu moj, molimo Te na ovom putu za dobročinstvo i bogobojaznost i djela koja Te zadovoljavaju. Allahu moj, olakšaj nam put i skrati nam udaljenost.',
    },
    reference: 'Muslim 1342',
    repeat: 1,
  },
  {
    id: 'travel-3',
    categoryId: 'travel',
    arabic: 'اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ',
    transliteration: 'Allahu Akbar, Allahu Akbar, Allahu Akbar. (When ascending) — SubhanAllah, SubhanAllah, SubhanAllah. (When descending)',
    translation: {
      en: 'When ascending a height say Allahu Akbar three times. When descending say SubhanAllah three times.',
      bs: 'Pri penjanju uzbrdo reci Allahu ekber tri puta. Pri silasku reci SubhanAllah tri puta.',
    },
    reference: 'Abu Dawud 2599 · Hasan',
    repeat: 3,
  },

  // ─── Eating ────────────────────────────────────────────────
  {
    id: 'eating-1',
    categoryId: 'eating',
    arabic: 'بِسْمِ اللَّهِ',
    transliteration: 'Bismillah',
    translation: {
      en: 'In the name of Allah. (Say before eating; if you forget, say when you remember.)',
      bs: 'U ime Allaha. (Reci prije jela; ako zaboraviš, reci kad se sjetiš.)',
    },
    reference: 'Abu Dawud 3767 · Tirmidhi 1858',
    repeat: 1,
  },
  {
    id: 'eating-2',
    categoryId: 'eating',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَٰذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ',
    transliteration: 'Alhamdu lillahil-ladhi at\'amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah.',
    translation: {
      en: 'All praise is for Allah who fed me this and provided it for me without any power or might from me.',
      bs: 'Hvala Allahu koji me nahranio ovim i dao mi bez moje snage i moći.',
    },
    reference: 'Tirmidhi 3458 · Hasan',
    repeat: 1,
    virtue: {
      en: 'Past sins are forgiven.',
      bs: 'Prošli grijesi se opraštaju.',
    },
  },
  {
    id: 'eating-3',
    categoryId: 'eating',
    arabic: 'اللَّهُمَّ بَارِكْ لَنَا فِيهِ وَأَطْعِمْنَا خَيْرًا مِنْهُ',
    transliteration: 'Allahumma barik lana fihi wa at\'imna khayran minh.',
    translation: {
      en: 'O Allah, bless it for us and feed us something better than it. (When drinking milk)',
      bs: 'Allahu moj, blagoslovi nam ovo i nahrani nas boljim od ovoga. (Pri piću mlijeka)',
    },
    reference: 'Tirmidhi 3285 · Hasan',
    repeat: 1,
  },
  {
    id: 'eating-4',
    categoryId: 'eating',
    arabic: 'اللَّهُمَّ بَارِكْ لَنَا فِيمَا رَزَقْتَنَا وَقِنَا عَذَابَ النَّارِ',
    transliteration: 'Allahumma barik lana fima razaqtana wa qina \'adhaban-nar.',
    translation: {
      en: 'O Allah, bless us in what You have provided us and protect us from the punishment of the Fire. (Before a meal)',
      bs: 'Allahu moj, blagoslovi nam u onome što si nam dao i sačuvaj nas od kazne Vatre. (Prije jela)',
    },
    reference: 'Tirmidhi 3458 · Hasan',
    repeat: 1,
  },
  {
    id: 'eating-5',
    categoryId: 'eating',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ',
    transliteration: 'Alhamdu lillahil-ladhi at\'amana wa saqana wa ja\'alana muslimin.',
    translation: {
      en: 'All praise is for Allah who fed us, gave us drink, and made us Muslims.',
      bs: 'Hvala Allahu koji nas je nahranio, napojio i učinio muslimanima.',
    },
    reference: 'Abu Dawud 3850 · Hasan',
    repeat: 1,
  },

  // ─── Mosque ────────────────────────────────────────────────
  {
    id: 'mosque-1',
    categoryId: 'mosque',
    arabic: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
    transliteration: 'Allahumm aftah li abwaba rahmatik.',
    translation: {
      en: 'O Allah, open for me the doors of Your mercy. (When entering the masjid)',
      bs: 'Allahu moj, otvori mi vrata Svoje milosti. (Pri ulasku u džamiju)',
    },
    reference: 'Muslim 713',
    repeat: 1,
  },
  {
    id: 'mosque-2',
    categoryId: 'mosque',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',
    transliteration: 'Allahumma inni as\'aluka min fadlik.',
    translation: {
      en: 'O Allah, I ask You from Your bounty. (When leaving the masjid)',
      bs: 'Allahu moj, molim Te iz Tvoje milosti. (Pri izlasku iz džamije)',
    },
    reference: 'Muslim 713',
    repeat: 1,
  },
  {
    id: 'mosque-3',
    categoryId: 'mosque',
    arabic: 'اللَّهُمَّ اجْعَلْ فِي قَلْبِي نُورًا، وَفِي لِسَانِي نُورًا، وَفِي سَمْعِي نُورًا، وَفِي بَصَرِي نُورًا',
    transliteration: 'Allahummaj\'al fi qalbi nuran, wa fi lisani nuran, wa fi sam\'i nuran, wa fi basari nuran.',
    translation: {
      en: 'O Allah, place light in my heart, light on my tongue, light in my hearing, and light in my sight.',
      bs: 'Allahu moj, stavi svjetlost u moje srce, na moj jezik, u moj sluh i u moj vid.',
    },
    reference: 'Bukhari 6316 · Muslim 763',
    repeat: 1,
  },

  // ─── Wudu ──────────────────────────────────────────────────
  {
    id: 'wudu-1',
    categoryId: 'wudu',
    arabic: 'بِسْمِ اللَّهِ',
    transliteration: 'Bismillah.',
    translation: {
      en: 'In the name of Allah. (When beginning wudu)',
      bs: 'U ime Allaha. (Pri početku abdesta)',
    },
    reference: 'Abu Dawud 101 · Tirmidhi 25',
    repeat: 1,
  },
  {
    id: 'wudu-2',
    categoryId: 'wudu',
    arabic: 'أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ',
    transliteration: 'Ashhadu an la ilaha illallahu wahdahu la sharika lah, wa ashhadu anna Muhammadan \'abduhu wa rasuluh.',
    translation: {
      en: 'I bear witness that none has the right to be worshipped except Allah, alone, without partner, and I bear witness that Muhammad is His servant and Messenger. (After completing wudu)',
      bs: 'Svjedočim da nema boga osim Allaha, Jednog, bez partnera, i svjedočim da je Muhammed Njegov rob i Poslanik. (Poslije abdesta)',
    },
    reference: 'Muslim 234',
    repeat: 1,
    virtue: {
      en: 'The eight gates of Paradise are opened for him and he may enter through whichever he wishes.',
      bs: 'Otvaraju mu se osam kapija Dženneta i može ući kroz koju god poželi.',
    },
  },
  {
    id: 'wudu-3',
    categoryId: 'wudu',
    arabic: 'اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ',
    transliteration: 'Allahummaj\'alni minat-tawwabina waj\'alni minal-mutatahhirin.',
    translation: {
      en: 'O Allah, make me among those who constantly repent and make me among those who purify themselves.',
      bs: 'Allahu moj, učini me među onima koji se često kaju i među onima koji se pročišćavaju.',
    },
    reference: 'Tirmidhi 55 · Sahih',
    repeat: 1,
  },
  {
    id: 'wudu-4',
    categoryId: 'wudu',
    arabic: 'سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا أَنْتَ، أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ',
    transliteration: 'Subhanakallahumma wa bihamdik, ashhadu an la ilaha illa ant, astaghfiruka wa atubu ilayk.',
    translation: {
      en: 'Glory be to You, O Allah, and praise be to You. I bear witness that none has the right to be worshipped except You. I seek Your forgiveness and repent to You. (After wudu)',
      bs: 'Slava Tebi, Allahu moj, i hvala Tebi. Svjedočim da nema boga osim Tebe. Tražim Tvoj oprost i kajem se Tebi. (Poslije abdesta)',
    },
    reference: 'Nasai al-Kubra · Sahih',
    repeat: 1,
  },
];

export function getZikrByCategory(categoryId: string) {
  return ZIKR_ITEMS.filter((item) => item.categoryId === categoryId);
}

export function getZikrCategory(categoryId: string) {
  return ZIKR_CATEGORIES.find((c) => c.id === categoryId);
}
